### PR TITLE
Adds Continuous Integration on ScaLAPACK

### PR DESCRIPTION
**Pull request by weslleyspereira**
Adds simple example that builds ScaLAPACK using GNU make.

Note that:
1. The workflow finishes as expected. See: https://github.com/weslleyspereira/scalapack/actions/runs/1948529370
2. I tried to add a workflow for MacOS. In the process I found an implicit function declaration: (note that option `-Werror=implicit-function-declaration` is active by default on MacOS based on https://github.com/RTimothyEdwards/magic/issues/69#issuecomment-897273888)

```make
cgsum2d_.c:230:10: error: implicit declaration of function 'BI_svmcopy' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
         BI_cvmcopy(Mpval(m), Mpval(n), A, tlda, bp->Buff); 
```

3. I tried to add a workflow for CMake. I still couldn't compile ScaLAPACK using CMake in my personal computer.

### CODE REVIEW

**Comment by weslleyspereira** [comment]
I tried to add a workflow for CMake. I still couldn't compile ScaLAPACK using CMake in my personal computer. The reason:
   - I can compile the library scalapack.
   - I couldn't build the tests because there are several undefined reference errors related to the MPI interface. I believe I should include the dependency on the MPI library somewhere.
   
Does anyone know how to compile ScaLAPACK using CMake on a Linux machine? Thanks!

**Comment by joseeroman** [comment]
On macOS I am using `-Wno-implicit-function-declaration` in `CFLAGS`

**Comment by weslleyspereira** [comment]
The current CI has:
- Build using GNU Make on Linux. This workflow runs all the examples on the EXAMPLES folder. 
- Build using CMake on Linux. This workflow runs all tests. Note that some of the tests fail (see https://github.com/weslleyspereira/scalapack/runs/5468949186).

**Comment by Baljak** [comment]
Looks great, do you think that a Windows build could be added using Mingw?

**Comment by weslleyspereira** [comment]
> Looks great, do you think that a Windows build could be added using Mingw?

That is the idea. As soon as the CI is working for Linux, it would be great to have it working for Windows and MacOS.

Currently, I am facing the following problem: The GitHub-hosted runners only have 2 cores (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners), and some of the tests in ScaLAPACK need at least 4 MPI processes. Those tests, therefore, take too long to complete. Does anyone have an idea to improve this workflow? Thanks!

**Comment by weslleyspereira** [comment]
One example of how using 2 MPI processes instead of 4 changed the times on the Github workflow:

Using 4 MPI processes for every test: (https://github.com/weslleyspereira/scalapack/runs/5471640656) (still running)
``` 
      Start 44: xzhrd
32/70 Test #44: xzhrd ............................   Passed  120.30 sec
```

Using 2 MPI processes whenever possible: (https://github.com/weslleyspereira/scalapack/runs/5472056161)
```
      Start 44: xzhrd
54/70 Test #44: xzhrd ............................   Passed    0.04 sec
```

The only difference between 2baaae6 and 28ff3c8 is the number of MPI processes I am using.

This a recent workflow using 4 MPI processes per test: https://github.com/weslleyspereira/scalapack/runs/5472056161. Total time 3h30min. The workflow https://github.com/weslleyspereira/scalapack/runs/5472056161 finished with 1h10min.

Amongst the tests using 4 MPI processes, the following take more than 10min to complete:
```
 The following tests FAILED:
	 65 - xssyevr (Timeout)
	 66 - xdsyevr (Timeout)
	 67 - xcheevr (Timeout)
	 68 - xzheevr (Timeout)
```

**Comment by joseeroman** [comment]
A workaround would be to use a self-hosted runner. Or change the tests (if possible) so that they use 2 processes at most.

**Comment by weslleyspereira** [comment]
> A workaround would be to use a self-hosted runner. Or change the tests (if possible) so that they use 2 processes at most.

Thanks! Yes, I found those two approaches. I was hoping there was some other configuration on the GIthub side that could help us. So far, I reduced the number of MPI processes for all the tests that allowed me to do so.

**Comment by weslleyspereira** [comment]
Hi. I think I got everything working good. To summarize:

This PR adds 2 Github Workflows to ScaLAPACK.
- The first one builds with GNU Make and tests the examples.
- Second one builds with CMake and runs all tests.
- This PR also fix bugs on the CMake build system (same fix from #57).
- `${MPIEXEC_PREFLAGS}` was added to the test executables. This allow for passing flags to mpiexec.

I rebased all commits to simplify the log. I think this PR is ready to go.

Again: It would be great to have recipes working for Windows and MacOS. But I think we should merge the current modifications just to have some tests in place.

**Comment by weslleyspereira** [comment]
> Looks great, do you think that a Windows build could be added using Mingw?

Hi! I started a discussion on #60. Maybe you want to comment on that.

**Pull request merged**
