### PR TITLE
Update MPI linking, building tests

### LINKED ISSUE #66: MPI not linked during build?
This issue covers apparently very basic build trouble on the path to package ScaLAPACK for pkgsrc, so I hope an issue is warranted. I do have changes to suggest, too, convering handling of dependencies (.pc file), but first the current version should at least build …

I might be too obvious, but I have trouble building scalapack 2.2.0. CMake lokates my compiler/MPI setup just fine:
```
$ mkdir b
$ cd b
$ cmake -DMPI_BASE_DIR=$(dirname $(dirname $(which mpicxx))) -DBUILD_SHARED_LIBS=on ..
[…]
-- Found MPI_C: /stuff/sw/env/gcc-10.3.0/pkgsrc/cvs-20210222/lib/libmpi.so (found version "3.0") 
-- Found MPI_Fortran: /stuff/sw/env/gcc-10.3.0/pkgsrc/cvs-20210222/lib/libmpi_usempif08.so (found version "3.0") 
-- Found MPI: TRUE (found version "3.0")  
-- Found MPI_LIBRARY : TRUE 
-- --> MPI C Compiler : /stuff/sw/env/gcc-10.3.0/pkgsrc/cvs-20210222/bin/mpicc
-- --> C Compiler : /stuff/sw/env/gcc-10.3.0/pkgsrc/cvs-20210222/bin/mpicc
-- --> MPI Fortran Compiler : /stuff/sw/env/gcc-10.3.0/pkgsrc/cvs-20210222/bin/mpif90
-- --> Fortran Compiler : /usr/bin/gfortran
```
But it doesn't even try to link to MPI, apparently:
```
[ 69%] Building Fortran object TESTING/LIN/CMakeFiles/xslu.dir/pslafchk.f.o
[ 69%] Linking Fortran executable ../xslu
/usr/bin/ld: ../../lib/libscalapack.so: undefined reference to `ompi_mpi_op_sum'
/usr/bin/ld: ../../lib/libscalapack.so: undefined reference to `MPI_Bcast'
/usr/bin/ld: ../../lib/libscalapack.so: undefined reference to `MPI_Op_create'
/usr/bin/ld: ../../lib/libscalapack.so: undefined reference to `MPI_Pack_size'
/usr/bin/ld: ../../lib/libscalapack.so: undefined reference to `MPI_Send'
/usr/bin/ld: ../../lib/libscalapack.so: undefined reference to `ompi_mpi_packed'
```
and, obviously

```
$ ldd lib/libscalapack.so 
        linux-vdso.so.1 (0x00007ffe647b2000)
        libopenblas.so.0 => /stuff/sw/env/gcc-10.3.0/pkgsrc/cvs-20210222/lib/libopenblas.so.0 (0x00007f4f73090000)
        libpthread.so.0 => /lib/libpthread.so.0 (0x00007f4f73057000)
        libgfortran.so.5 => /usr/lib/libgfortran.so.5 (0x00007f4f72ea0000)
        libm.so.6 => /lib/libm.so.6 (0x00007f4f72ddc000)
        libdl.so.2 => /lib/libdl.so.2 (0x00007f4f72dd7000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f4f72dbf000)
        libquadmath.so.0 => /usr/lib/libquadmath.so.0 (0x00007f4f72d81000)
        libc.so.6 => /lib/libc.so.6 (0x00007f4f72bf6000)
        /lib/ld-linux-x86-64.so.2 (0x00007f4f75245000)
```
Shouldn't there be a reference to libmpi?

I also don't see e.g. `MPI_LIBRARIES`,  `MPI_LINK_FLAGS`, or  anything like that used in CMakeLists.txt. I guess it is supposed to make more use of the MPI compiler wrappers? How is this supposed to work? (Note: Don't be fooled by the cvs-20210222 name, it is a current checkout of the pkgsrc tree, which I am trying to add scalapack to.)

When I tried to hack in use of `MPI_LIBRARIES`, the main MPI symbols were resolved, but I still had some missing ones at some stage. So, before I dive too deep, I hoped to get some clarification that the build should normally `just work` or that I'm doing something wrong. I did have a working draft installation of scalapack-2.1.0 before. I might have to revisit why that worked.

### PR DESCRIPTION
**Pull request by Rickbude**
Various improvements (hopefully) to MPI linking. Summary:
* Bump CMake version to 3.9, such that find_package(MPI) exports the targets MPI::MPI_C, MPI::MPI_Fortran etc
* Remove `INCLUDE_DIRECTORIES(${MPI_INCLUDE_PATH})`: include path should be tied to the MPI targets described above
* Replace `target_link_libraries(some_target ${MPI_Fortran_LIBRARIES})` with `target_link_libraries(some_target MPI::MPI_Fortran)`
* Link scalapack with MPI::MPI_C (should fix #66)

Aside from this I noticed two variables were used for building tests: `SCALAPACK_BUILD_TESTING` and `SCALAPACK_BUILD_TESTS`. Only the latter had an associated cache variable, so I assumed all instances should be the latter.

### CODE REVIEW

**Review by weslleyspereira — APPROVED** [review]
Thanks! The changes look great to me

**Comment by Rickbude** [comment]
I just noticed a mistake in the main CMakeLists at line 250-254:

```
add_library(scalapack ${blacs} ${tools-C} ${pblas} ${ptools} ${redist} ${src-C} MPI::MPI_C)
...
target_link_libraries( scalapack ${LAPACK_LIBRARIES} ${BLAS_LIBRARIES})
```

which will result in configure errors under MSVC, should instead be:
```
add_library(scalapack ${blacs} ${tools-C} ${pblas} ${ptools} ${redist} ${src-C})
...
target_link_libraries( scalapack ${LAPACK_LIBRARIES} ${BLAS_LIBRARIES}  MPI::MPI_C)
```

Is there a way to edit my pull request, or should I just cancel this pull request and create a new one?

**Comment by drhpc** [comment]
I tried this in my pkgsrc attempt (#66), after adapting the patch to this state:

[patch-2.2.0-PR67.txt](https://github.com/Reference-ScaLAPACK/scalapack/files/9142123/patch-2.2.0-PR67.txt)

The result seems to work in linking to MPI now in the installed library. But the file list changed. I wonder if that is intentional.
```
$ bmake print-PLIST
@comment $NetBSD$
lib/cmake/scalapack-2.1.0/scalapack-config-version.cmake
lib/cmake/scalapack-2.1.0/scalapack-config.cmake
lib/cmake/scalapack-2.1.0/scalapack-targets-noconfig.cmake
lib/cmake/scalapack-2.1.0/scalapack-targets.cmake
lib/libscalapack.so
lib/pkgconfig/scalapack.pc
```
So this is only the shared lib and strangely a directory versioned with 2.1.0, not 2.2.0. The old list of files looked like that:
```
$ cat PLIST 
@comment $NetBSD$
lib/cmake/${PKGNAME}/scalapack-config-version.cmake
lib/cmake/${PKGNAME}/scalapack-config.cmake
lib/cmake/${PKGNAME}/scalapack-targets-noconfig.cmake
lib/cmake/${PKGNAME}/scalapack-targets.cmake
lib/libscalapack.a
lib/libscalapack.so
lib/pkgconfig/scalapack.pc
```
PKGNAME is scalapack-2.2.0 in this case. I am not sure if there's some interaction with the build system around it to cause this. Where does the version number come from? And also: Is it intentional that the static library is not built anymore?

**Comment by Rickbude** [comment]
> . Where does the version number come from? And also: Is it intentional that the static library is not built anymore?

To be honest, I don't know how the changes I made to the CMakeLists could result in the differences you mentioned. Are you building in both cases from a clean git clone, empty CMake cache, and identical build flags (so e.g. BUILD_SHARED_LIBS=ON|OFF in both cases)? If you give me your exact configure and build commands I can give it a try and try to replicate the observed behavior.

**Comment by drhpc** [comment]
(I am not building from a git checkout, but trying to package a released version of ScaLAPACK, so it is 2.2.0 + patches.)

Well, I am comparing with the previously working (somewhat) build of scalapack 2.1.0. There, the version number of the cmake files matches. Now, in release 2.2.0, I see this in CMakeLists.txt:

```
set(SCALAPACK_VERSION 2.1.0)
set(CPACK_PACKAGE_VERSION_MAJOR 2)
set(CPACK_PACKAGE_VERSION_MINOR 1)
set(CPACK_PACKAGE_VERSION_PATCH 0)
```

Is it intentional to have that not in sync with the package release version? Regarding the shared/static libs, it's probably a surprise that the static lib was built before, too, with 2.1.0. What is the intention of the upstream project here? I used to care a lot for keeping static and shared libs installed for LAPACK, as static was the old-school default, actually tried to submit changes to that build to enable both shared and static lib build in one go.

I am now tending towards not giving a **** and just getting on with life, so only the shared lib is fine by me. My only question, then, is if the SCALAPACK_VERSION in the build should match the released version.

**Comment by drhpc** [comment]
Sure I am looking at outdated code — the current official release;-) I see that #46 fixed that. I wonder if your intended ABI policy is appropriate, though. If the SONAME is always libscalapack.so.MAJOR.MINOR … are you intending for version 2.3 not to be backwards compatible to version 2.2? I have a project where I took care to only add API and keep the old symbols working, over many dozen minor version increases now. The SONAME is still libfoo.so.0, with the full version being libfoo.so.0.47.0  (the 47th ABI update without patchlevel. A binary built with the first library release still works with the freshest one. I consider that being nice to users.

Is the ABI of 2.2.x supposed to be a subset of the ABI of 2.3.x, hence symlinking the library would work for old binaries? Or is it considered a full ABI break? Would be nice to clarify that in the docs. Then, you please be careful in increasing the minor version of ScaLAPACK to avoid too frequent program breakage with updates;-)

But back to the original issue: Yes, MPI linking seems fine now with the changes of this PR ported to 2.2.0 release for my purposes.

**Comment by drhpc** [comment]
I cannot reproduce the case of shared and static liblapack being built now. Maybe that was an artifact of the build debugging with some inconsistent state. I'll default to only the shared lib now.

**Comment by weslleyspereira** [comment]
> Well, I am comparing with the previously working (somewhat) build of scalapack 2.1.0. There, the version number of the cmake files matches. Now, in release 2.2.0, I see this in CMakeLists.txt:
> 
> ```
> set(SCALAPACK_VERSION 2.1.0)
> set(CPACK_PACKAGE_VERSION_MAJOR 2)
> set(CPACK_PACKAGE_VERSION_MINOR 1)
> set(CPACK_PACKAGE_VERSION_PATCH 0)
> ```
> 
> Is it intentional to have that not in sync with the package release version?

Not intentional. I think we could (github-)release ScaLAPACK with the current master + this PR. It would solve this and a couple of other issues. 

> If the SONAME is always libscalapack.so.MAJOR.MINOR … are you intending for version 2.3 not to be backwards compatible to version 2.2? I have a project where I took care to only add API and keep the old symbols working, over many dozen minor version increases now. The SONAME is still libfoo.so.0, with the full version being libfoo.so.0.47.0 (the 47th ABI update without patchlevel. A binary built with the first library release still works with the freshest one. I consider that being nice to users.
> 
> Is the ABI of 2.2.x supposed to be a subset of the ABI of 2.3.x, hence symlinking the library would work for old binaries? Or is it considered a full ABI break? Would be nice to clarify that in the docs. Then, you please be careful in increasing the minor version of ScaLAPACK to avoid too frequent program breakage with updates;-)

We had no policy, so not good. Then we adopted one in #48. This policy says that libscalapack.so.2.3 may not be ABI-compatible to libscalapack.so.2.2. This is similar to what they are using for Debian. Please, feel free to open a new issue to address this. We may, for instance, modify the policy a bit and use libscalapack.so.MAJOR.MINOR.PATCH. I just think this thread is not ideal to start this discussion. 

> Regarding the shared/static libs, it's probably a surprise that the static lib was built before, too, with 2.1.0. What is the intention of the upstream project here? I used to care a lot for keeping static and shared libs installed for LAPACK, as static was the old-school default, actually tried to submit changes to that build to enable both shared and static lib build in one go.
> 
> I am now tending towards not giving a **** and just getting on with life, so only the shared lib is fine by me. My only question, then, is if the SCALAPACK_VERSION in the build should match the released version.

In #61, there was a change in the behavior of `BUILD_STATIC_LIBS`. However, I am not sure when ScaLAPACK had a build with shared and static libs. I tried v2.2.0 in my Linux machine with `BUILD_STATIC_LIBS=ON` and `BUILD_SHARED_LIBS=ON` and obtained only `libscalapack.so`. Actually, I don't know how `BUILD_STATIC_LIBS` is used in the building process. This is not standard in CMake. Also, I recommend we continue this discussion in another thread.

**Pull request merged**
